const AppAction = {
    LOADING_APP_START: 'LOADING_APP_START',
    CLOSE_LOADING_APP: 'CLOSE_LOADING_APP',
    LOADING_APP_POPUP_START: 'LOADING_APP_POPUP_START',
    CLOSE_LOADING_APP_POPUP: 'CLOSE_LOADING_APP_POPUP',

    FETCH_SAMPLE_1: 'FETCH_SAMPLE_1',
    FETCH_SAMPLE_1_SUCCESS: 'FETCH_SAMPLE_1_SUCCESS',
    FETCH_SAMPLE_1_ERROR: 'FETCH_SAMPLE_1_ERROR',

    FETCH_SAMPLE_2: 'FETCH_SAMPLE_2',
    FETCH_SAMPLE_2_SUCCESS: 'FETCH_SAMPLE_2_SUCCESS',
    FETCH_SAMPLE_2_ERROR: 'FETCH_SAMPLE_2_ERROR',

    FETCH_GET_DATA: 'FETCH_GET_DATA',
    FETCH_GET_DATA_SUCCESS: 'FETCH_GET_DATA_SUCCESS',

    FETCH_GET_DATA_ID: 'FETCH_GET_DATA_ID',
    FETCH_GET_DATA_ID_SUCCESS: 'FETCH_GET_DATA_ID_SUCCESS',

    FETCH_POST_DATA: 'FETCH_POST_DATA',
    FETCH_POST_DATA_SUCCESS: 'FETCH_POST_DATA_SUCCESS',

};

export default AppAction;
